# Generated by Django 5.0.7 on 2024-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_role_customuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
