# Generated by Django 5.0.7 on 2024-08-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='Unassigned', max_length=30),
        ),
    ]
