# Generated by Django 5.0.7 on 2024-07-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_date_created_department_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
