# Generated by Django 5.0.7 on 2024-07-27 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
